services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - api_net

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:80"
    environment:
      - DSN=postgresql://postgres:password@postgres_auth:5432/users?sslmode=disable
    networks:
      - api_net
    

  postgres_auth:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql
    networks:
      - api_net

networks:
  api_net:
   
